import Head from "next/head";
import Image from "next/image";
// import { Inter } from "next/font/google";
import { Card, Button, Input } from "shuddle";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Shuddle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card kind="C1" background="#eee">
        <Card.Img accent="#888">
          <Image src="/me.jpeg" width={870} height={881} />
        </Card.Img>
        <Card.Body>UX Unicorn</Card.Body>
      </Card>

      <Button rounded={false} outline={false}>
        Normal Solid
      </Button>

      <Input from="Detroit" to="Las Vegas" />
    </>
  );
}
